assets_path: data/assets # put either absolute path or relative to current directory
g_dataset_path: data/g_dataset
ig_dataset_path: data/ig_dataset
threedfront_dataset_path: data/threedfront_dataset
cubicasa_dataset_path: data/cubicasa_dataset
key_path: data/igibson.key
demo_name_path: ./igibson/data/demo_names.json
subgoal_prompt_root_path: ./igibson/evaluation/eval_subgoal_plan/resources